create database testA;


USE testA;
CREATE TABLE CLIENTE (
    NRO_CLIENTE bigint NOT NULL primary key,
    DNI bigint not null ,
    APELLIDO varchar(50) DEFAULT NULL,
    NOMBRE varchar(50) DEFAULT NULL ,
    DIRECCION varchar(100) DEFAULT NULL,
    TELEFONO varchar(25) DEFAULT NULL
);

CREATE TABLE FACTURA (
    NRO_FACTURA VARCHAR(12) NOT NULL primary key,
    NRO_CLIENTE bigint DEFAULT NULL,
    FECHA date DEFAULT NULL,
    MONTO DECIMAL(10,2),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (NRO_CLIENTE) REFERENCES CLIENTE(NRO_CLIENTE) 
);

DELIMITER $$
CREATE TRIGGER triggerCheckNroTelefono
BEFORE INSERT 
ON CLIENTE FOR EACH ROW
BEGIN
    IF (LEN(NEW.TELEFONO)>10) THEN 
        signal sqlstate '45000' set message_text ='NUMERO ERRADO NO CONTIENE 10 o menos CARACTERES';
    END IF;
END; $$
DELIMITER ; 

DELIMITER //
CREATE PROCEDURE total_facturas_mayores_a
()
BEGIN
  SELECT COUNT(*) FROM FACTURA;
END //

