create database testB;

USE testB;
CREATE TABLE CLIENTE (
    NRO_CLIENTE bigint NOT NULL,
    DNI bigint not null primary key,
    APELLIDO varchar(50) DEFAULT NULL,
    NOMBRE varchar(50) DEFAULT NULL ,
    DIRECCION varchar(100) DEFAULT NULL,
    TELEFONO varchar(25) DEFAULT NULL
);

CREATE TABLE FACTURA (
    NRO_FACTURA VARCHAR(12) NOT NULL primary key,
    NRO_CLIENTE bigint DEFAULT NULL,
    FECHA date DEFAULT NULL,
    MONTO DECIMAL(10,2),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (NRO_CLIENTE) REFERENCES CLIENTE(DNI) 
);

DELIMITER $$
CREATE TRIGGER triggerCheckNroTelefono
AFTER INSERT 
ON CLIENTE FOR EACH ROW
BEGIN
    IF (LEN(NEW.TELEFONO)>10) THEN 
        signal sqlstate '45000' set message_text ='NUMERO ERRADO NO CONTIENE 10 o menos CARACTERES';
    END IF;
END; $$
DELIMITER ;

DELIMITER //
CREATE PROCEDURE total_facturas_mayores_a
(IN monto2 DECIMAL(10,2))
BEGIN
  SELECT COUNT(*) FROM FACTURA
  WHERE MONTO > monto2;
END //